// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjwwptukjmlfdzvwusqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtqd3dwdHVram1sZmR6dnd1c3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTcwODUsImV4cCI6MjA2NTU5MzA4NX0.VXycHgR0vaAgBbKQuOQIWbWOXClqyPpQ1SQ8CnzoHLw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);